version: '2'

services:
  <%= serviceName %>:
    image: <%= imageName %><% if (environment === 'debug') { %>:debug<% } %>
    build:
      context: .
      dockerfile: Dockerfile<% if (environment === 'debug') { %>.debug<% } %><% if (isWebProject && portNumber) { %>
    ports:
      - "<%= portNumber %>:<%= portNumber %>"<% } %><% if (environment === 'debug') { %><% if (debugPortNumber) { %>
      - "<%= debugPortNumber %>:<%= debugPortNumber %>"<% } %><% if (volumeMap) { %>
    volumes:
      - <%= volumeMap %><% } %><% if (includeComposeForDebug) { %>
    environment:
      - REMOTE_DEBUGGING<% } %><% } %>
