version: '2'

services:
  <%= serviceName %>:<% if (environment === 'debug') { %>
    image: <%= imageName %>:debug<% } else { %>
    image: <%= imageName %><% } %><% if (isWebProject && portNumber) { %>
    ports:
      - "<%= portNumber %>:<%= portNumber %>"<% } %><% if (environment === 'debug') { %><% if (debugPortNumber) { %>
      - "<%= debugPortNumber %>:<%= debugPortNumber %>"<% } %><% if (volumeMap) { %>
    volumes:
      - <%= volumeMap %><% } %><% if (includeComposeForDebug) { %>
    environment:
      - REMOTE_DEBUGGING<% } %><% } %>
