version: '2'

services:
  <%= serviceName %>:<% if (environment === 'debug') { %>
    image: <%= imageName %>:debug<% } else { %>
    image: <%= imageName %><% } %><% if (isWebProject && portNumber) { %>
    ports:
      - "<%= portNumber %>:<%= portNumber %>"<% } %><% if (environment === 'debug') { %><% if (projectType === 'nodejs') { %>
      - "5858:5858"<% } %><% if (volumeMap !== null) { %>
    volumes:
      - <%= volumeMap %><% } %><% if (projectType === 'nodejs' || (projectType === 'dotnet' && dotnetVersion === 'RC2')) { %>
    environment:
      - REMOTE_DEBUGGING<% } %><% } %>
